levels:
- input:
    level: l0
    desc: raw
  output:
    level: l1a
    desc: all
- input:
    level: spice
    desc: historical
  output:
    level: l1a
    desc: all
- input:
    level: l1a
    desc: de
  output:
    level: l1b
    desc: de
- input:
    level: ancillary
    desc: l1b-conversion-table-for-anc-data
  output:
    level: l1b
    desc: de
- input:
    level: spice
    desc: historical
  output:
    level: l1b
    desc: hist
- input:
    level: ancillary
    desc: l1b-conversion-table-for-anc-data
  output:
    level: l1b
    desc: hist
- input:
    level: l1a
    desc: hist
  output:
    level: l1b
    desc: hist
- input:
    level: spin
    desc: historical
  output:
    level: l1b
    desc: hist
- input:
    level: ancillary
    desc: l1b-exclusions-by-instr-team
  output:
    level: l1b
    desc: hist
- input:
    level: ancillary
    desc: l1b-map-of-excluded-regions
  output:
    level: l1b
    desc: hist
- input:
    level: ancillary
    desc: l1b-map-of-uv-sources
  output:
    level: l1b
    desc: hist
- input:
    level: ancillary
    desc: pipeline-settings
  output:
    level: l1b
    desc: hist
- input:
    level: ancillary
    desc: l1b-suspected-transients
  output:
    level: l1b
    desc: hist
- input:
    level: spice
    desc: historical
  output:
    level: l2
    desc: hist
- input:
    level: l1b
    desc: hist
  output:
    level: l2
    desc: hist
- input:
    level: ancillary
    desc: pipeline-settings
  output:
    level: l2
    desc: hist
- input:
    level: ancillary
    desc: l2-calibration
  output:
    level: l2
    desc: hist
- input:
    level: ancillary
    desc: pipeline-settings
  output:
    level: l3a
    desc: hist
- input:
    level: l2
    desc: hist
  output:
    level: l3a
    desc: hist
- input:
    level: ancillary
    desc: calibration-data
  output:
    level: l3a
    desc: hist
- input:
    level: ancillary
    desc: l3a-time-dep-bckgrd
  output:
    level: l3a
    desc: hist
- input:
    level: ancillary
    desc: l3a-map-of-extra-helio-bckgrd
  output:
    level: l3a
    desc: hist
