levels:
- input:
    level: l0
    desc: raw
  output:
    level: l1
    desc: hk
- input:
    level: spice
    desc: historical
  output:
    level: l1
    desc: hk
- input:
    level: l0
    desc: raw
  output:
    level: l1
    desc: sci
- input:
    level: spice
    desc: historical
  output:
    level: l1
    desc: sci
- input:
    level: l1a
    desc: hk
  output:
    level: l1
    desc: sci
- input:
    level: l1
    desc: sci
  output:
    level: l2
    desc: sci
- input:
    level: ancillary
    desc: esa-unit-conversion
  output:
    level: l2
    desc: sci
- input:
    level: ancillary
    desc: lut-notes
  output:
    level: l2
    desc: sci
- input:
    level: l2
    desc: sci
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: clock-angle-and-flow-deflection-lut
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: proton-density-temperature-lut
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: alpha-density-temperature-lut
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: energy-gf-pui-lut
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: instrument-response-lut
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: density-of-neutral-helium-lut
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: efficiency-lut
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: helium-inflow-vector
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: ancillary
    desc: hydrogen-inflow-vector
  output:
    level: l3a
    desc: alpha-sw
- input:
    level: spice
    desc: historical
  output:
    level: l3a
    desc: proton-sw
- input:
    level: l2
    desc: sci
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: clock-angle-and-flow-deflection-lut
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: proton-density-temperature-lut
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: alpha-density-temperature-lut
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: energy-gf-pui-lut
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: instrument-response-lut
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: density-of-neutral-helium-lut
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: efficiency-lut
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: helium-inflow-vector
  output:
    level: l3a
    desc: proton-sw
- input:
    level: ancillary
    desc: hydrogen-inflow-vector
  output:
    level: l3a
    desc: proton-sw
- input:
    level: spice
    desc: historical
  output:
    level: l3a
    desc: pui-he
- input:
    level: l2
    desc: sci
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: clock-angle-and-flow-deflection-lut
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: proton-density-temperature-lut
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: alpha-density-temperature-lut
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: energy-gf-pui-lut
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: instrument-response-lut
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: density-of-neutral-helium-lut
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: efficiency-lut
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: helium-inflow-vector
  output:
    level: l3a
    desc: pui-he
- input:
    level: ancillary
    desc: hydrogen-inflow-vector
  output:
    level: l3a
    desc: pui-he
- input:
    level: l2
    desc: sci
  output:
    level: l3b
    desc: combined
- input:
    level: ancillary
    desc: efficiency-lut
  output:
    level: l3b
    desc: combined
- input:
    level: ancillary
    desc: energy-gf-sw-lut
  output:
    level: l3b
    desc: combined
