name: Validate Dependency YAMLs

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "2.3.4"

      - name: Install dependencies and app
        run: |
          poetry install

      - name: Validate dependency YAMLs
        run: |
          poetry run python scripts/dependency/validate_dependency_yamls.py

